# MCP Gateway CI/CD Pipeline
# Automatically builds, tests, and deploys MCP server + DevOps tools to ubuntu-devops.lan

trigger:
  branches:
    include:
    - master
    - main
  paths:
    include:
    - EnvironmentMCPGateway/*
    - docker-compose*
    - devops/*
    exclude:
    - README.md
    - docs/*

variables:
  DEVOPS_SERVER: 'ubuntu-devops.lan'
  DEVOPS_USER: 'alex'  # Updated to match your SSH user
  CONTAINER_REGISTRY: 'your-registry'  # Update if using custom registry

stages:
- stage: BuildAndTest
  displayName: 'Build and Test MCP Server'
  jobs:
  - job: BuildJob
    displayName: 'Build MCP Gateway'
    pool: Default
    
    steps:
    - checkout: self
      displayName: 'Checkout Repository'
      
    - task: NodeTool@0
      displayName: 'Setup Node.js'
      inputs:
        versionSpec: '20.x'
        
    - script: |
        cd EnvironmentMCPGateway
        npm ci
        npm run build
        npm run lint
      displayName: 'Build TypeScript MCP Server'
      
    - task: UseDotNet@2
      displayName: 'Setup .NET 9'
      inputs:
        packageType: 'sdk'
        version: '9.x'
        
    - script: |
        dotnet build LucidwonksMCPGateway.sln
        dotnet test EnvironmentMCPGateway.Tests/ --logger trx --results-directory TestResults --filter "FullyQualifiedName~Unit"
      displayName: 'Build and Test .NET Components (Unit Tests Only)'
      
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/TestResults/*.trx'
      condition: always()
      
    - script: |
        cd EnvironmentMCPGateway
        docker build -f docker/Dockerfile -t mcp-gateway:$(Build.BuildId) .
      displayName: 'Build Docker Image'
      
    - script: |
        docker save mcp-gateway:$(Build.BuildId) | gzip > mcp-gateway-$(Build.BuildId).tar.gz
      displayName: 'Export Docker Image'
      
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Docker Image'
      inputs:
        pathtoPublish: 'mcp-gateway-$(Build.BuildId).tar.gz'
        artifactName: 'docker-image'

- stage: Deploy
  displayName: 'Deploy to ubuntu-devops.lan'
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy MCP Server and Update DevOps Tools'
    environment: 'ubuntu-devops-lan'
    pool: Default
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: docker-image
            
          - task: CopyFilesOverSSH@0
            displayName: 'Copy Docker Image to Server'
            inputs:
              sshEndpoint: 'ubuntu-devops-ssh'  # Configure this service connection
              sourceFolder: '$(Pipeline.Workspace)/docker-image'
              contents: '*.tar.gz'
              targetFolder: '/tmp/mcp-deploy'
              
          - task: CopyFilesOverSSH@0
            displayName: 'Copy Deployment Files'
            inputs:
              sshEndpoint: 'ubuntu-devops-ssh'
              sourceFolder: '$(Build.SourcesDirectory)'
              contents: |
                docker-compose.production.yml
                .env.production
              targetFolder: '/opt/mcp-gateway'
              
          - task: SSH@0
            displayName: 'Load MCP Server Image'
            inputs:
              sshEndpoint: 'ubuntu-devops-ssh'
              runOptions: 'commands'
              failOnStderr: false
              commands: |
                echo "Loading MCP Gateway image..."
                docker load < /tmp/mcp-deploy/mcp-gateway-$(Build.BuildId).tar.gz
                docker tag mcp-gateway:$(Build.BuildId) mcp-gateway:latest
                echo "MCP Gateway image loaded successfully"
                
          - task: SSH@0
            displayName: 'Deploy Services'
            inputs:
              sshEndpoint: 'ubuntu-devops-ssh'
              runOptions: 'commands' 
              failOnStderr: false
              commands: |
                echo "Updating service images..."
                docker-compose -f /opt/mcp-gateway/docker-compose.production.yml pull >/dev/null 2>&1 || true
                
                echo "Restarting MCP Gateway with new build..."
                docker-compose -f /opt/mcp-gateway/docker-compose.production.yml stop environment-mcp-gateway || true
                docker-compose -f /opt/mcp-gateway/docker-compose.production.yml up -d
                
                echo "Cleaning up..."
                docker container prune -f >/dev/null 2>&1 || true
                rm -f /tmp/mcp-deploy/mcp-gateway-$(Build.BuildId).tar.gz
                
                echo "Deployment complete. Container status:"
                docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
                
          - task: SSH@0
            displayName: 'Health Check Services'
            inputs:
              sshEndpoint: 'ubuntu-devops-ssh'
              runOptions: 'commands'
              failOnStderr: false
              commands: |
                # Wait for services to be ready
                sleep 30
                
                # Show container status first
                echo "=== Container Status ==="
                docker ps -a
                
                echo "=== MCP Gateway Logs (last 50 lines) ==="
                docker logs --tail 50 environment-mcp-gateway || echo "No MCP Gateway logs available"
                
                echo "=== Network Status ==="
                docker network ls
                
                echo "=== Port Binding Check ==="
                netstat -tlnp | grep -E ":(3002|8080|9000)" || echo "No services bound to expected ports"
                
                # Check MCP Gateway health with more details
                echo "=== Testing MCP Gateway Health ==="
                curl -v http://localhost:3002/health || echo "MCP Gateway health check failed"
                
                # Check if container is actually running
                if docker ps | grep -q environment-mcp-gateway; then
                  echo "MCP Gateway container is running"
                else
                  echo "ERROR: MCP Gateway container is not running"
                  exit 1
                fi
                
                # Check Bytebase health  
                echo "=== Testing Bytebase Health ==="
                curl -f http://localhost:8080/api/ping || echo "Bytebase health check failed"
                
                # Check Portainer health
                echo "=== Testing Portainer Health ==="
                curl -f http://localhost:9000/api/system/status || echo "Portainer health check failed"
                
                echo "=== Health Check Summary Complete ==="