name: lucidwonks-environment

services:
  environment-mcp-gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: environment-mcp-gateway
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - MCP_SERVER_PORT=3001
      - MCP_TRANSPORT_TYPE=http
      - MCP_LOG_LEVEL=info
      - PROJECT_ROOT=/workspace
      # Use host database connection
      - DATABASE_URL=postgresql://postgres:password@host.docker.internal:5432/pricehistorydb
      # Set data directories to mounted volumes
      - ATOMIC_OPS_DIR=/app/.atomic-ops
      - HOLISTIC_ROLLBACK_DIR=/app/.holistic-rollback
      - HOLISTIC_OPS_DIR=/app/.holistic-ops
      - SEMANTIC_CACHE_DIR=/app/.semantic-cache
      # Required environment variables
      - DB_PASSWORD=password
      - GIT_USER_NAME=Environment MCP Gateway
      - GIT_USER_EMAIL=noreply@lucidwonks.com
      # Enhanced timeout configurations (in milliseconds)
      - SEMANTIC_ANALYSIS_TIMEOUT=90000
      - DOMAIN_ANALYSIS_TIMEOUT=60000
      - CONTEXT_GENERATION_TIMEOUT=75000
      - FILE_OPERATIONS_TIMEOUT=45000
      - FULL_REINDEX_TIMEOUT=600000
      - SINGLE_FILE_TIMEOUT=15000
      # Rollback cleanup configuration
      - ROLLBACK_MAX_AGE_HOURS=24
      - ROLLBACK_MAX_COUNT=10
      # Path resolution debugging
      - PATH_RESOLUTION_DEBUG=true
    env_file:
      - ../.env.development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${GIT_REPO_PATH:-M:/Projects/Lucidwonks}:/workspace
      # Persistent storage for MCP server data
      - mcp_cache:/app/.semantic-cache
      - mcp_rollback:/app/.holistic-rollback  
      - mcp_atomic:/app/.atomic-ops
      - mcp_holistic_ops:/app/.holistic-ops
    restart: unless-stopped
    networks:
      - environment-mcp-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "com.lucidwonks.service=environment-mcp-gateway"
      - "com.lucidwonks.version=1.0"

volumes:
  mcp_cache:
    driver: local
  mcp_rollback:
    driver: local
  mcp_atomic:
    driver: local
  mcp_holistic_ops:
    driver: local

networks:
  environment-mcp-network:
    driver: bridge
    name: environment-mcp-network